#!/usr/bin/env bash
# =============================================================================
# Qwen3-TTS: Mac Studio setup for the FILE-REF VOICE-CLONING server
# =============================================================================
# This is the server the Phenom dev-environment access layer (sablier-weblogon)
# drives. It clones a developer's voice from <id>_ref.wav + <id>_ref.txt files
# dropped in the server directory, and exposes the contract that layer requires:
#   GET  /v1/voices                 list the FILE-CLONED voices ({voices:[{id}]})
#   POST /v1/voices/reload          rescan the voices dir
#   POST /v1/voices/{id}/reclone    rebuild a voice's embedding
#
# It is DISTINCT from the CustomVoice server (scripts/setup-macstudio.sh), which
# serves the model's nine built-in speakers and does NOT do file-ref cloning.
#
# Server code (tts_server.py + backends/ + engine/effects/preprocess) is the proven
# SanMarcSoft reference deploy, brought in unchanged. The mlx-audio backend reads
# the model from TTS_QWEN_MODEL. The Mac Studio is capable, so the DEFAULT here is
# the HIGHER-QUALITY 1.7B Base MLX build; set TTS_QWEN_MODEL to the lighter
# 0.6B-Base-4bit on RAM-constrained hosts (that is what the constrained reference
# box ran).
#
# Idempotent. Usage:
#   ./scripts/setup-cloning-macstudio.sh                 # venv + deps + model (1.7B bf16)
#   TTS_QWEN_MODEL=mlx-community/Qwen3-TTS-12Hz-0.6B-Base-4bit ./scripts/setup-cloning-macstudio.sh
#   ./scripts/setup-cloning-macstudio.sh --no-model      # skip the model pre-download
# =============================================================================
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; cd "$REPO_ROOT"

VENV_DIR="${QWEN_TTS_CLONING_VENV:-$REPO_ROOT/.venv-cloning}"
MODEL_ID="${TTS_QWEN_MODEL:-mlx-community/Qwen3-TTS-12Hz-1.7B-Base-bf16}"   # higher quality (Mac Studio)
DOWNLOAD_MODEL=1; [ "${1:-}" = "--no-model" ] && DOWNLOAD_MODEL=0

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[err]\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. Host sanity ---------------------------------------------------------
[ "$(uname -s)" = "Darwin" ] || warn "Not macOS; this targets the Mac Studio; continuing."
[ "$(uname -m)" = "arm64" ] || warn "Not arm64 — MLX/Metal unavailable; cloning falls back to CPU (slow)."
command -v python3 >/dev/null 2>&1 || die "python3 not found (brew install python@3.12 or Xcode CLT)."

# --- 2. venv (prefer uv) ----------------------------------------------------
if command -v uv >/dev/null 2>&1; then
  say "Creating venv with uv at $VENV_DIR"; uv venv "$VENV_DIR" >/dev/null
  PIP=(uv pip install --python "$VENV_DIR/bin/python")
else
  say "uv not found; python3 -m venv at $VENV_DIR"; python3 -m venv "$VENV_DIR"
  "$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
  PIP=("$VENV_DIR/bin/python" -m pip install --upgrade)
fi

# --- 3. cloning-server deps (mlx-audio backend) -----------------------------
say "Installing cloning-server requirements"
"${PIP[@]}" -r server/requirements-cloning.txt
"${PIP[@]}" "huggingface_hub[cli]" >/dev/null

# --- 4. model -----------------------------------------------------------------
if [ "$DOWNLOAD_MODEL" = 1 ]; then
  say "Pre-downloading $MODEL_ID (the backend also pulls it on first run)"
  "$VENV_DIR/bin/huggingface-cli" download "$MODEL_ID" >/dev/null \
    || warn "model pre-download failed; the server will pull it on first run"
else
  warn "Skipping model pre-download (--no-model); server pulls $MODEL_ID on first run."
fi

# --- 5. .env-cloning for the run script -------------------------------------
say "Writing $REPO_ROOT/.env-cloning"
cat > "$REPO_ROOT/.env-cloning" <<EOF
# Generated by setup-cloning-macstudio.sh; read by scripts/run-cloning-server.sh.
TTS_QWEN_MODEL=$MODEL_ID
TTS_DEFAULT_BACKEND=qwen
# Voices dir = THIS repo dir: engine.py scans its own directory for <id>_ref.wav/.txt.
# The sablier-weblogon voice-enrollment container bind-mounts this dir as /tts-voices.
EOF

say "Setup complete (file-ref cloning server)."
cat <<EOF

  Start:        ./scripts/run-cloning-server.sh
  Auto-start:   ./scripts/run-cloning-server.sh --install-launchd   # com.phenom.qwen3-tts
  Verify the cloning contract:
    curl -s http://127.0.0.1:8880/v1/voices
    curl -s -X POST http://127.0.0.1:8880/v1/voices/reload
  Model: $MODEL_ID
    (higher quality for the Mac Studio; use ...0.6B-Base-4bit on constrained hosts)
EOF
