#!/usr/bin/env bash
# =============================================================================
# Qwen3-TTS: Mac Studio (bare-metal) setup for the Phenom voice server
# =============================================================================
# Sets up the Qwen3-TTS OpenAI-compatible speech server on the Mac Studio so that
# PAI and every Code Server container can reach a single shared voice endpoint.
#
# The server runs on the HOST (bare metal, Apple Silicon / MPS), NOT in a
# container, because the model needs native Metal acceleration. Containers reach
# it across the container->host boundary at http://host.docker.internal:8880.
#
# Idempotent: safe to re-run. See docs/SERVER_SETUP.md for the full guide.
#
# Usage:
#   ./scripts/setup-macstudio.sh                 # full setup (venv + deps + model)
#   QWEN_TTS_MODEL=Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice ./scripts/setup-macstudio.sh
#   ./scripts/setup-macstudio.sh --no-model      # skip the (large) model download
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VENV_DIR="${QWEN_TTS_VENV:-$REPO_ROOT/.venv}"
MODEL_ID="${QWEN_TTS_MODEL:-Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice}"
TOKENIZER_ID="Qwen/Qwen3-TTS-Tokenizer-12Hz"
MODELS_DIR="${QWEN_TTS_MODELS_DIR:-$REPO_ROOT/models}"
PORT="${QWEN_TTS_PORT:-8880}"
DOWNLOAD_MODEL=1
[ "${1:-}" = "--no-model" ] && DOWNLOAD_MODEL=0

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[err]\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. Host sanity checks --------------------------------------------------
say "Checking host (expecting macOS / Apple Silicon)"
[ "$(uname -s)" = "Darwin" ] || warn "Not macOS; this script targets the Mac Studio; continuing anyway."
if [ "$(uname -m)" != "arm64" ]; then
  warn "Not arm64; MPS acceleration unavailable; the server will fall back to CPU (slow)."
fi
command -v python3 >/dev/null 2>&1 || die "python3 not found. Install via Xcode CLT or Homebrew (brew install python@3.11)."

# --- 2. Python environment (prefer uv, fall back to venv) -------------------
if command -v uv >/dev/null 2>&1; then
  say "Creating virtualenv with uv at $VENV_DIR"
  uv venv "$VENV_DIR" >/dev/null
  PIP=(uv pip install --python "$VENV_DIR/bin/python")
else
  say "uv not found; using python3 -m venv at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
  PIP=("$VENV_DIR/bin/python" -m pip install --upgrade)
  "$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
fi

# --- 3. Install the package + server deps -----------------------------------
say "Installing qwen_tts (editable) + server requirements"
"${PIP[@]}" -e .
"${PIP[@]}" -r server/requirements.txt
"${PIP[@]}" "huggingface_hub[cli]" >/dev/null

# --- 4. Download the model + tokenizer --------------------------------------
if [ "$DOWNLOAD_MODEL" = "1" ]; then
  mkdir -p "$MODELS_DIR"
  local_model="$MODELS_DIR/$(basename "$MODEL_ID")"
  local_tok="$MODELS_DIR/$(basename "$TOKENIZER_ID")"
  say "Downloading model $MODEL_ID -> $local_model (this is several GB)"
  "$VENV_DIR/bin/huggingface-cli" download "$MODEL_ID" --local-dir "$local_model"
  say "Downloading tokenizer $TOKENIZER_ID -> $local_tok"
  "$VENV_DIR/bin/huggingface-cli" download "$TOKENIZER_ID" --local-dir "$local_tok"
  RESOLVED_MODEL="$local_model"
else
  warn "Skipping model download (--no-model). The server will pull $MODEL_ID from HF on first run."
  RESOLVED_MODEL="$MODEL_ID"
fi

# --- 5. Write a .env the run script reads -----------------------------------
say "Writing $REPO_ROOT/.env"
cat > "$REPO_ROOT/.env" <<EOF
# Generated by setup-macstudio.sh; edit as needed.
QWEN_TTS_MODEL=$RESOLVED_MODEL
QWEN_TTS_HOST=0.0.0.0          # 0.0.0.0 so Code Server containers can reach it via host.docker.internal
QWEN_TTS_PORT=$PORT
QWEN_TTS_DEVICE=mps            # Apple Silicon Metal; use "cpu" to force CPU
QWEN_TTS_DTYPE=bfloat16
QWEN_TTS_DEFAULT_LANGUAGE=Auto
# QWEN_TTS_DEFAULT_SPEAKER=     # leave blank to use the model's first supported speaker
# Map PAI's voice name to a Qwen speaker, e.g. {"narrator":"Ethan"}:
# QWEN_TTS_VOICE_ALIASES={"narrator":"Ethan"}
# RECOMMENDED when binding 0.0.0.0: shared bearer token for all clients:
# QWEN_TTS_API_KEY=change-me
EOF

say "Setup complete."
cat <<EOF

  Start the server:        ./scripts/run-server.sh
  Auto-start at login:     ./scripts/run-server.sh --install-launchd
  Health check (host):     curl -s http://127.0.0.1:$PORT/readyz
  List the model's voices: curl -s http://127.0.0.1:$PORT/v1/voices

  From a Code Server container, the server is reachable at:
      http://host.docker.internal:$PORT/v1

  Point PAI's voice at that endpoint (see docs/SERVER_SETUP.md, "Wire the containers").
EOF
